### ISSUE TITLE
Question regarding texture array size

### ISSUE THREAD

**Issue by io7m** [khalladay/VulkanDemoProjects#1]
Hello!

I enjoyed reading your "Using Arrays of Textures in Vulkan Shaders" blog post. It cleared up a few things I'd been wondering about during my attempt to educate myself about Vulkan having only known OpenGL 3.3.

One thing I'm curious about: Do you happen to know what parts of the Vulkan spec might indicate sensible maximum values for the sizes of texture arrays? I'd like to size my arrays based on reported device capabilities.

**Comment by io7m** [comment]
To answer my own question years later: The relevant device limit is `maxPerStageDescriptorSampledImages`, which is `8388606` on my `AMD RADV NAVI10` workstation.

**Comment by khalladay** [comment]
Sorry I missed this years ago, glad you found the answer though :)

**Comment by io7m** [comment]
No problem. I get enough GitHub notifications to miss a few dozen here and there. :smile:
